# Generated by Django 4.2.6 on 2023-11-12 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_perfil_options_alter_perfil_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
