# Generated by Django 4.2.6 on 2023-11-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_perfil_date_joined_perfil_is_active_perfil_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
