# Generated by Django 4.2.7 on 2023-11-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_administradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
