# Generated by Django 4.2.6 on 2023-10-31 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('id_locales', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('correo', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('subcategoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subcategoria', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('subcategoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBodega',
            fields=[
                ('id_detalle_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bodegas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
    ]
