# Generated by Django 4.2.6 on 2023-10-31 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='last_name',
        ),
    ]
