# Generated by Django 4.2.6 on 2023-10-31 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_perfil_first_name_remove_perfil_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='correo',
        ),
    ]
