# Generated by Django 4.2.6 on 2023-10-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_perfil_fecha_creacion_alter_perfil_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
