# Generated by Django 4.2.6 on 2023-10-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_administrador_cliente_locales_usuario_clienteperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
