# Generated by Django 4.2.6 on 2023-10-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_perfil_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
