# Generated by Django 4.2.6 on 2023-10-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_administrador_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
