# Generated by Django 4.2.6 on 2023-11-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_perfil_is_staff_alter_perfil_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
