# Generated by Django 4.2.6 on 2023-10-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0006_administrador_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='administradores', to='auth.group'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='administrador',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='administrador',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='administradores', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
