# Generated by Django 4.2.6 on 2023-10-24 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_administrador_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='token',
        ),
    ]
