# Generated by Django 4.0.4 on 2023-10-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_administrador_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBodega',
            fields=[
                ('id_detalle_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bodegas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
    ]
